---
- name: Copy compiled files
  become: true
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/

- name: Stop and delete already running server
  become: true
  ignore_errors: true
  shell: |
    pm2 kill

- name: Start server
  become: true
  shell: |
    env

    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start

  # environment: 
  #   TYPEORM_CONNECTION: "postgres" 
  #   TYPEORM_ENTITIES: "./src/modules/domain/**/*.entity.ts"
  #   TYPEORM_HOST: database-1.cnqfywmnaaqa.us-east-1.rds.amazonaws.com
  #   TYPEORM_PORT: "5432"
  #   TYPEORM_USERNAME: postgres
  #   TYPEORM_PASSWORD: 48T6V^ziBMQxhp8
  #   TYPEORM_DATABASE: postgres
  #   TYPEORM_MIGRATIONS: "./src/migrations/*.ts"
  #   TYPEORM_MIGRATIONS_DIR: "./src/migrations" 
  
  # environment:
  #   ENVIRONMENT: production
  #   TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}" 
  #   TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES')}}"
  #   TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
  #   TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_HOST')}}"
  #   TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
  #   TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
  #   TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
  #   TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
  #   TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}" 
  
